#!/bin/bash
git config --local user.email "action@github.com"
git config --local user.name "GitHub Action Bot"

BRANCH_NAME="docs/multi-lang-$(date +%Y%m%d-%H%M%S)"
git checkout -b "$BRANCH_NAME"
git add .
git commit -m "${COMMIT_MESSAGE}

- Added/updated AI_CONTEXT.md for AI context
- Generated Go docstrings for exported functions
- Generated TypeScript TSDoc comments for exports
- Generated Python docstrings for functions and classes
- Processed ${{ steps.find-files.outputs.total_files }} files total

Generated by: Auto Documentation & Docstrings Action"

git push origin "$BRANCH_NAME"

echo "branch_created=$BRANCH_NAME" >> $GITHUB_OUTPUT

echo "## 🎯 Multi-Language Documentation Update Complete!" >> $GITHUB_STEP_SUMMARY
echo "**Review Branch**: \`$BRANCH_NAME\`" >> $GITHUB_STEP_SUMMARY
echo "**Total Files Processed**: ${{ steps.find-files.outputs.total_files }}" >> $GITHUB_STEP_SUMMARY
