name: Auto Documentation & Docstrings

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      model_provider:
        description: 'AI Model Provider'
        required: false
        default: 'anthropic'
        type: choice
        options:
        - anthropic
        - gemini

jobs:
  auto-documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Auto Documentation & Docstrings
        uses: devasy23/auto-documentation-action@v1
        with:
          model_provider: ${{ github.event.inputs.model_provider || 'anthropic' }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          target_branches: 'main,develop'
          commit_message: 'docs: Auto-generated multi-language documentation'
